In [ ]:
# Титаник
import pandas as pd
import numpy as np

!unzip titanic.zip

Archive:  titanic.zip
  inflating: gender_submission.csv
  inflating: test.csv
  inflating: train.csv

In [ ]:
df = pd.read_csv("train.csv")
df.sample(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
747,748,1,2,"Sinkkonen, Miss. Anna",female,30.0,0,0,250648,13.0000,NaN,S
402,403,0,3,"Jussila, Miss. Mari Aina",female,21.0,1,0,4137,9.8250,NaN,S
725,726,0,3,"Oreskovic, Mr. Luka",male,20.0,0,0,315094,8.6625,NaN,S
106,107,1,3,"Salkjelsvik, Miss. Anna Kristine",female,21.0,0,0,343120,7.6500,NaN,S
85,86,1,3,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...",female,33.0,3,0,3101278,15.8500,NaN,S
848,849,0,2,"Harper, Rev. John",male,28.0,0,1,248727,33.0000,NaN,S
414,415,1,3,"Sundman, Mr. Johan Julian",male,44.0,0,0,STON/O 2. 3101269,7.9250,NaN,S
359,360,1,3,"Mockler, Miss. Helen Mary ""Ellie""",female,NaN,0,0,330980,7.8792,NaN,Q
174,175,0,1,"Smith, Mr. James Clinch",male,56.0,0,0,17764,30.6958,A7,C
793,794,0,1,"Hoyt, Mr. William Fisher",male,NaN,0,0,PC 17600,30.6958,NaN,C

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
# Половозрастная структура
a = df['Age'][df.Sex == 'male'].agg(['mean', 'min', 'max'])
b = df['Age'][df.Sex == 'female'].agg(['mean', 'min', 'max'])

print(f'Средний возраст мужчины: {a[0]}')
print(f'Средний возраст женщины: {b[0]}')

print(f'Минимальный возраст мужчины: {a[1]}')
print(f'Максимальный возраст женщины: {b[1]}')

print(f'Минимальный возраст мужчины: {a[2]}')
print(f'Минимальный возраст женщины: {b[2]}')

Средний возраст мужчины: 30.72664459161148
Средний возраст женщины: 27.915708812260537
Минимальный возраст мужчины: 0.42
Максимальный возраст женщины: 0.75
Минимальный возраст мужчины: 80.0
Минимальный возраст женщины: 63.0

In [ ]:
# Создал колонку возратсных групп
df['AgeGroup'] = range(len(df))

for i in range(len(df)):
  if df.Age[i] < 18:
    df['AgeGroup'][i] = 'Child'
  elif df.Age[i] < 60 and df.Age[i] >= 18:
    df['AgeGroup'][i] = 'Adult'
  elif df.Age[i] > 60:
    df['AgeGroup'][i] = 'Old man'
  else:
    df['AgeGroup'][i] = None


df.sample(10)

<ipython-input-13-6059ecf09e02>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['AgeGroup'][i] = 'Adult'

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,AgeGroup
488,489,0,3,"Somerton, Mr. Francis William",male,30.0,0,0,A.5. 18509,8.0500,NaN,S,Adult
535,536,1,2,"Hart, Miss. Eva Miriam",female,7.0,0,2,F.C.C. 13529,26.2500,NaN,S,Child
773,774,0,3,"Elias, Mr. Dibo",male,NaN,0,0,2674,7.2250,NaN,C,None
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C,Adult
182,183,0,3,"Asplund, Master. Clarence Gustaf Hugo",male,9.0,4,2,347077,31.3875,NaN,S,Child
673,674,1,2,"Wilhelms, Mr. Charles",male,31.0,0,0,244270,13.0000,NaN,S,Adult
579,580,1,3,"Jussila, Mr. Eiriik",male,32.0,0,0,STON/O 2. 3101286,7.9250,NaN,S,Adult
654,655,0,3,"Hegarty, Miss. Hanora ""Nora""",female,18.0,0,0,365226,6.7500,NaN,Q,Adult
583,584,0,1,"Ross, Mr. John Hugo",male,36.0,0,0,13049,40.1250,A10,C,Adult
396,397,0,3,"Olsson, Miss. Elina",female,31.0,0,0,350407,7.8542,NaN,S,Adult

In [ ]:
# Вероятность выживаемости мужчины по его возрастной группе
a = df['Age'][df.Sex == 'male'].groupby(df.AgeGroup).agg('count')
b= df['Age'][df.Sex == 'male'][df.Survived == 1].groupby(df.AgeGroup).agg('count')
b / a * 100

AgeGroup
Adult      17.962466
Child      39.655172
Old man    10.526316
Name: Age, dtype: float64

In [ ]:
# Вероятность выживаемости женщины по её возрастной группе
c = df['Age'][df.Sex == 'female'].groupby(df.AgeGroup).agg('count')
d= df['Age'][df.Sex == 'female'][df.Survived == 1].groupby(df.AgeGroup).agg('count')
d / c * 100

AgeGroup
Adult       76.732673
Child       69.090909
Old man    100.000000
Name: Age, dtype: float64

In [ ]:
#Половозрастная структура по выжившим и нет
print(df[['Survived', 'Age', 'Sex']][df.Survived == 1].groupby('Sex').agg({'Age': ['mean', 'median']}))
df[['Survived', 'Age', 'Sex']][df.Survived == 0].groupby('Sex').agg({'Age': ['mean','median']})

              Age
             mean median
Sex
female  28.847716   28.0
male    27.276022   28.0

              Age
             mean median
Sex
female  25.046875   24.5
male    31.618056   29.0

In [ ]:
# Количество пустых значений
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
AgeGroup       181
dtype: int64

In [ ]:
# Средняя стоимость билета
mean_fare = df['Fare'].mean()
print(f'Средняя цена билета: {mean_fare}')

Средняя цена билета: 32.204207968574636

In [ ]:
# Средняя стоимость билета выжившего
mean_fare = df['Fare'][df.Survived == 1].mean()
print(f'Средняя цена билета: {mean_fare}')

Средняя цена билета: 48.39540760233918

In [ ]:
# Влияние класса на выживаемость
a = df['Survived'][df.Survived == 1].groupby(df.Pclass).count()
b = df['Survived'].groupby(df.Pclass).count()
a / b * 100

Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64

In [ ]:
# Сопоставить колонки Fare и Embarked
df[['Fare', 'Embarked']].groupby('Embarked').agg({'Fare' : ['mean', 'max', 'mean']})

/usr/local/lib/python3.10/dist-packages/google/colab/_dataframe_summarizer.py:40: PerformanceWarning: indexing past lexsort depth may impact performance.
  dtype = df[column].dtype

               Fare
               mean       max       mean
Embarked
C         59.954144  512.3292  59.954144
Q         13.276030   90.0000  13.276030
S         27.079812  263.0000  27.079812

In [ ]:
# Количество выживжих в зависимости от порта
df[['Survived', 'Embarked']].groupby('Embarked').agg('sum')

          Survived
Embarked
C               93
Q               30
S              217

In [ ]:
# Зависимость выживаемости от порта
a = df[['Survived', 'Embarked']][df.Survived == 1].groupby('Embarked').agg('count')
b= df[['Survived', 'Embarked']].groupby('Embarked').agg('count')
a / b * 100

           Survived
Embarked
C         55.357143
Q         38.961039
S         33.695652

In [ ]:
# Количество выживших младенцев (до 1 года)
alive = df['Name'][df.Age < 1][df.Survived == 1].count()
dead = df['Name'][df.Age < 1][df.Survived == 0].count()

print(f'{alive} младенцев были спасены, погибших {dead}')

7 младенцев были спасены, погибших 0

In [ ]:
sorted_df = df.sort_values('Name').head(15)
sorted_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,AgeGroup
845,846,0,3,"Abbing, Mr. Anthony",male,42.0,0,0,C.A. 5547,7.5500,NaN,S,Adult
746,747,0,3,"Abbott, Mr. Rossmore Edward",male,16.0,1,1,C.A. 2673,20.2500,NaN,S,Child
279,280,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.0,1,1,C.A. 2673,20.2500,NaN,S,Adult
308,309,0,2,"Abelson, Mr. Samuel",male,30.0,1,0,P/PP 3381,24.0000,NaN,C,Adult
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C,Adult
365,366,0,3,"Adahl, Mr. Mauritz Nils Martin",male,30.0,0,0,C 7076,7.2500,NaN,S,Adult
401,402,0,3,"Adams, Mr. John",male,26.0,0,0,341826,8.0500,NaN,S,Adult
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,NaN,S,Adult
855,856,1,3,"Aks, Mrs. Sam (Leah Rosen)",female,18.0,0,1,392091,9.3500,NaN,S,Adult
207,208,1,3,"Albimona, Mr. Nassef Cassem",male,26.0,0,0,2699,18.7875,NaN,C,Adult
810,811,0,3,"Alexander, Mr. William",male,26.0,0,0,3474,7.8875,NaN,S,Adult
840,841,0,3,"Alhomaki, Mr. Ilmari Rudolf",male,20.0,0,0,SOTON/O2 3101287,7.9250,NaN,S,Adult
210,211,0,3,"Ali, Mr. Ahmed",male,24.0,0,0,SOTON/O.Q. 3101311,7.0500,NaN,S,Adult
784,785,0,3,"Ali, Mr. William",male,25.0,0,0,SOTON/O.Q. 3101312,7.0500,NaN,S,Adult
730,731,1,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,Adult

In [ ]:
# Выделяем стобец с фамилиями
df['LastName'] = df['Name'].apply(lambda x: x.split(',')[0])
# Отбираем группы с количеством одинаковых фамилий > 1
relatives = df.groupby(['LastName', 'Ticket']).filter(lambda x: len(x) > 1)
families = relatives[(df.SibSp > 0) | (df.Parch > 0)]
# Находим количество семей
num_families = families.groupby(['LastName', 'Ticket']).ngroups
num_families

<ipython-input-38-02ea3c45272d>:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  families = relatives[(df.SibSp > 0) | (df.Parch > 0)]

97

In [ ]:
# Как находить братьев-сестёр, супругов и т.д., я не понимаю